name: YIJIANROOT 一键 ROOT（兼容性一般，但较快）

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/tissot/20230425/lineage-19.1-20230425-nightly-tissot-signed.zip'
      zip_name:
        description: 'ZIP 包名称'
        required: true
        default: 'TOSASITILL_YIJIANROOT'
      ver:
        description: 'Magisk 版本(24.3/25.2/26.1)'
        required: true
        default: '24.3'

jobs:
  YIJIANROOT:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get -y install aria2 7z
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV

      - name: 提取镜像
        run: |
          cd ${{ github.workspace }}
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          unzip firmware.zip
          chmod +x ./payload-dumper-go
          ./payload-dumper-go -p boot,init_boot -o ~/output payload.bin

      - name: 创建镜像信息
        run: |
          cd ${{ github.workspace }}
          touch info.md
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "ROM 下载直链：${{ github.event.inputs.rom_url }}" >> info.md
          echo "Magisk 修补版本：${{ github.event.inputs.ver }}" >> info.md
          cd ~/output/
          if [ -f "init_boot.img" ]; then rm boot.img; fi
          du -h --total *.img | sed 's/^/修补镜像大小： /' | head -n 1 >> ${{ github.workspace }}/info.md

      - name: 创建一键 ROOT ZIP
        run: |
          cd ~
          git clone https://github.com/tosasitill/YIJIANROOT_add.git -b "${{ github.event.inputs.ver }}" XIUBU
          chmod -R +x XIUBU
          cd XIUBU
          mv ~/output/* ./
          mkdir done
          ./boot.sh
          cd ~
          git clone https://github.com/tosasitill/YIJIANROOT_add.git "${{ github.event.inputs.zip_name }}"
          mv ~/XIUBU/done/*.img ~/${{ github.event.inputs.zip_name }}
          cd ${{ github.event.inputs.zip_name }}
          rm -rf .git
          cd ~
          7z a -tzip -mx9 ${{ github.event.inputs.zip_name }}.zip ${{ github.event.inputs.zip_name }}/
          pwd
          ls

      - name: 上传至 TMP CloudDrive
        run: |
          curl -k -F "file=@/home/runner/${{ github.event.inputs.zip_name }}.zip" -F "token=${{ secrets.TMP }}" -F "model=0"  -X POST  "https://connect.tmp.link/api_v2/cli_uploader"
          sed -i '5d' ${{ github.workspace }}/info.md && sed -i 's/Download Page/下载链接/g' ${{ github.workspace }}/info.md

      - name: 上传 ZIP 及镜像信息
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "~/${{ github.event.inputs.zip_name }}.zip"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
            token: ${{ secrets.GITHUB_TOKEN }}

